### ISSUE TITLE
Overwrite could preserve author and committer data

### ISSUE THREAD

**Issue by BlankSpruce** [wozniakpl/hashcommit#1]
Before using the tool author and committer data looks like this:
```
$ git log -1 --pretty=format:"%an / %ae / %ad" && git log -1 --pretty=format:"%cn / %ce / %cd"
Bartosz Woźniak / 17177420+wozniakpl@users.noreply.github.com / Thu May 23 19:08:08 2024 +0200
Bartosz Woźniak / 17177420+wozniakpl@users.noreply.github.com / Thu May 23 19:08:08 2024 +0200
```
After calling `python3 ./hashcommit/main.py --overwrite --hash 123 --message "update readme" --match-type begin` it transforms into:
```
git log -1 --pretty=format:"%an / %ae / %ad" && git log -1 --pretty=format:"%cn / %ce / %cd"    
Blank Spruce / 32396809+BlankSpruce@users.noreply.github.com / Thu May 23 18:07:53 2024 +0000
Blank Spruce / 32396809+BlankSpruce@users.noreply.github.com / Thu May 23 18:07:53 2024 +0000
```
I'd be nice to preserve original author and committer data. 

It'd be also nice if overwrite mode didn't require providing commit message since user can leverage `commit --amend` to do that in two-step solution
1. Amend the commit message or commit content however you like as usual.
2. Improve commit hash with this tool.

The following feature request may or may not be used for forging stuff. 

Excellent tool idea. :laughing:

**Comment by wozniakpl** [comment]
Thank you for the feedback! Once I get some testing environment up and running, this should be easy to achieve.

**Comment by wozniakpl** [comment]
It should be possible now to preserve the author and commiter data. Only the commiter's date changes, so the hash comes out different.

Also, it's possible to explicitly not preserve author's and commiter's data with `--no-preserve-author`.
